export enum ActionKeys {
    // Persisted
    CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES',
    SET_THEME_CONFIG = 'SET_THEME_CONFIG',
    // Runtime
    SET_LAST_CHECKED = 'SET_LAST_CHECKED',
    SET_ERROR = 'SHOW_ERROR',
    SET_NEW_VERSION = 'SET_NEW_VERSION',
    SET_CONFIG_LOCATION = 'SET_CONFIG_LOCATION',
    OPEN_DIALOG = 'OPEN_DIALOG',
    SET_THEMES = 'SET_THEMES',
    RESTORE_PERSISTED_STATE = 'RESTORE_PERSISTED_STATE',
}
